import { 
  Animal, 
  User, 
  VetDoctor, 
  FarmExpense, 
  OutbreakReport, 
  OfflineKnowledgeItem, 
  Appointment, 
  DairyProduct,
  AdminUserItem,
  UserApplication,
  UserComplaint,
  SystemReport,
  AdminNotification,
  SupportMessageThread,
  AIActivityLog,
  AdminAuditLogEntry,
  AdminSystemSettings
} from '../types';

export const initialUser: User = {
  id: 'usr_001',
  name: 'Chaudhry Ahmed Ali',
  phone: '0300-1234567',
  email: 'ahmed.farm@kisandost.ai',
  farmName: 'Al-Madina Dairy & Cattle Farm',
  location: 'Chak 88/9-L, Sahiwal, Punjab',
  district: 'Sahiwal',
  language: 'ur',
  isPremium: true,
  hasCompletedOnboarding: false,
  createdAt: '2026-01-10T10:00:00Z',
};

export const initialAnimals: Animal[] = [
  {
    id: 'anm_001',
    ownerId: 'usr_001',
    tagId: 'KD-8842',
    name: 'Sahiwal Queen (سوہنی)',
    species: 'cow',
    breed: 'Pure Sahiwal Breed',
    gender: 'female',
    ageMonths: 48,
    weightKg: 485,
    dob: '2022-08-15',
    purchasePrice: 320000,
    currentMarketValue: 385000,
    marketValueChangePercent: 20.3,
    importStatus: false,
    bloodline: 'Royal Sahiwal Champion Line',
    sireInfo: 'Sahiwal Stud King-01',
    damInfo: 'Sahiwal Beauty-88',
    pregnancyStatus: 'lactating',
    pregnancyMonths: 0,
    milkYieldLitersPerDay: 18.5,
    healthScore: 92,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [
      {
        id: 'vac_101',
        animalId: 'anm_001',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth Disease',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: 'completed',
      },
      {
        id: 'vac_102',
        animalId: 'anm_001',
        vaccineName: 'LSD (لمپی سکن)',
        diseaseTarget: 'Lumpy Skin Disease',
        dateGiven: '2026-01-15',
        nextDueDate: '2027-01-15',
        administeredBy: 'Dr. Tariq Mahmood',
        status: 'completed',
      },
      {
        id: 'vac_103',
        animalId: 'anm_001',
        vaccineName: 'HS (گل گھوٹو)',
        diseaseTarget: 'Hemorrhagic Septicemia',
        dateGiven: '2025-11-20',
        nextDueDate: '2026-08-20',
        administeredBy: 'Dr. Sanaullah',
        status: 'scheduled',
      }
    ],
    medicalHistory: [
      {
        id: 'med_001',
        animalId: 'anm_001',
        date: '2026-05-12',
        diagnosis: 'Mild Udder Swelling (مستائٹس ابتداء)',
        treatment: 'Intramammary Infusion & Anti-inflammatory',
        medicineGiven: 'Penicillin + Oxytetracycline',
        dosage: '10ml IM daily for 3 days',
        vetName: 'Dr. Tariq Mahmood',
        recoveryStatus: 'cured',
      }
    ],
    scanJournal: [
      {
        id: 'scn_001',
        animalId: 'anm_001',
        animalName: 'Sahiwal Queen',
        date: '2026-05-12 09:30 AM',
        imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
        detectedDisease: 'Early Mastitis (تھنوں کی سوجن)',
        confidence: 94,
        severity: 'mild',
        causes: ['Bacterial infection in milk duct', 'Improper milking hygiene', 'Wet bedding area'],
        precautions: ['Isolate milking bucket', 'Clean udder with warm antiseptic water', 'Keep bedding dry'],
        recommendedMedicines: ['Mammitis Teat Dip Solution', 'Amoxicillin Inj. 15mg/kg'],
        vetRequired: true,
        recoveryDaysEstimate: 5,
        aiNotes: 'Early detection saved milk quality. Animal recovered in 4 days.',
      }
    ],
    auditLogs: [
      {
        id: 'aud_001',
        timestamp: '2026-07-01 10:15 AM',
        fieldChanged: 'Weight (kg)',
        oldValue: '470 kg',
        newValue: '485 kg',
        updatedBy: 'Chaudhry Ahmed Ali',
      }
    ],
    ownershipHistory: [
      {
        id: 'own_001',
        date: '2023-01-10',
        sellerName: 'Sahiwal Government Breeding Farm',
        buyerName: 'Chaudhry Ahmed Ali',
        buyerPhone: '0300-1234567',
        salePrice: 320000,
        certificateNumber: 'PK-SAH-2023-8842',
      }
    ],
    digitalLicenseNumber: 'PK-LIVESTOCK-8842-SAH',
    insuranceDetails: {
      policyNumber: 'Takaful-Live-90921',
      provider: 'Pak-Qatar Livestock Takaful',
      insuredValue: 350000,
      startDate: '2026-01-01',
      expiryDate: '2027-01-01',
      status: 'active',
    },
    createdAt: '2023-01-10',
    updatedAt: '2026-07-01',
  },

  {
    id: 'anm_002',
    ownerId: 'usr_001',
    tagId: 'KD-9102',
    name: 'Nili Beauty (نیلی رانی)',
    species: 'buffalo',
    breed: 'Nili-Ravi Pure Breed',
    gender: 'female',
    ageMonths: 36,
    weightKg: 580,
    dob: '2023-05-20',
    purchasePrice: 410000,
    currentMarketValue: 480000,
    marketValueChangePercent: 17.0,
    importStatus: false,
    bloodline: 'Nili-Ravi High-Milk Line',
    sireInfo: 'Kasur Champion Bull-99',
    damInfo: 'Okara Queen Buffalo',
    pregnancyStatus: 'pregnant',
    pregnancyMonths: 6,
    milkYieldLitersPerDay: 16.0,
    healthScore: 89,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [
      {
        id: 'vac_201',
        animalId: 'anm_002',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth Disease',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: 'completed',
      }
    ],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    digitalLicenseNumber: 'PK-LIVESTOCK-9102-NILI',
    createdAt: '2023-06-01',
    updatedAt: '2026-06-15',
  },

  {
    id: 'anm_003',
    ownerId: 'usr_001',
    tagId: 'KD-5510',
    name: 'Gulabi Prince (گلابی شیرا)',
    species: 'goat',
    breed: 'Gulabi Kamori Cross',
    gender: 'male',
    ageMonths: 18,
    weightKg: 72,
    dob: '2025-01-10',
    purchasePrice: 75000,
    currentMarketValue: 110000,
    marketValueChangePercent: 46.6,
    importStatus: true,
    countryOfOrigin: 'Sindh Pedigree Farm',
    importLicenseNumber: 'IMP-GOAT-2025-11',
    bloodline: 'Kamori Royal Pink Line',
    sireInfo: 'Sindh Champion Stud',
    damInfo: 'Sindh Beauty Goat',
    pregnancyStatus: 'none',
    milkYieldLitersPerDay: 0,
    healthScore: 96,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [
      {
        id: 'vac_301',
        animalId: 'anm_003',
        vaccineName: 'PPR (پپی آر بکریوں کی وبا)',
        diseaseTarget: 'Peste des Petits Ruminants',
        dateGiven: '2026-02-01',
        nextDueDate: '2027-02-01',
        administeredBy: 'Dr. Sanaullah',
        status: 'completed',
      }
    ],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    digitalLicenseNumber: 'PK-GOAT-PEDIGREE-5510',
    createdAt: '2025-01-15',
    updatedAt: '2026-07-10',
  },

  {
    id: 'anm_004',
    ownerId: 'usr_001',
    tagId: 'KD-1002',
    name: 'Sahiwal Sultan (سلطان سانڈ)',
    species: 'cow',
    breed: 'Pure Sahiwal Stud Bull',
    gender: 'male',
    ageMonths: 54,
    weightKg: 710,
    dob: '2022-02-10',
    purchasePrice: 550000,
    currentMarketValue: 680000,
    marketValueChangePercent: 23.6,
    importStatus: true,
    countryOfOrigin: 'Sahiwal National Genetics Center',
    importLicenseNumber: 'NAT-GEN-2022-009',
    bloodline: 'Elite Breeding Bull A-1',
    sireInfo: 'Sahiwal Legend Sire',
    damInfo: 'Sahiwal Super Mother 30L',
    pregnancyStatus: 'none',
    milkYieldLitersPerDay: 0,
    healthScore: 84,
    healthStatus: 'fair',
    isQuarantined: false,
    photos: [
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [
      {
        id: 'vac_401',
        animalId: 'anm_004',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: 'completed',
      }
    ],
    medicalHistory: [
      {
        id: 'med_401',
        animalId: 'anm_004',
        date: '2026-06-20',
        diagnosis: 'Hoof Inflammation & Mild Fever',
        treatment: 'Antiseptic hoof bandage & Paracetamol Inj',
        medicineGiven: 'Meloxicam + Copper Sulphate Wash',
        dosage: '15ml IM for 2 days',
        vetName: 'Dr. Tariq Mahmood',
        recoveryStatus: 'recovering',
      }
    ],
    scanJournal: [
      {
        id: 'scn_401',
        animalId: 'anm_004',
        animalName: 'Sahiwal Sultan',
        date: '2026-06-20 11:00 AM',
        imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
        detectedDisease: 'Hoof Rot / Foot Swelling (سم کی سوزش)',
        confidence: 91,
        severity: 'moderate',
        causes: ['Wet muddy ground', 'Bacterial entry into hoof fissure'],
        precautions: ['Keep in dry clean yard', 'Apply hoof antiseptic dip daily'],
        recommendedMedicines: ['Oxytetracycline Hoof Spray', 'Flunixin Meglumine'],
        vetRequired: true,
        recoveryDaysEstimate: 7,
        aiNotes: 'Under treatment. Improving nicely.',
      }
    ],
    auditLogs: [],
    ownershipHistory: [],
    digitalLicenseNumber: 'PK-PEDIGREE-BULL-1002',
    createdAt: '2022-03-01',
    updatedAt: '2026-06-25',
  }
];

export const initialMarketplaceListings: Animal[] = [
  {
    id: 'mkt_001',
    ownerId: 'mkt_owner_01',
    tagId: 'MND-7712',
    name: 'Sahiwal Red Champion (لال پری)',
    species: 'cow',
    breed: 'Pure Sahiwal Grade-A',
    gender: 'female',
    ageMonths: 38,
    weightKg: 460,
    dob: '2023-04-10',
    purchasePrice: 310000,
    currentMarketValue: 360000,
    marketValueChangePercent: 16.1,
    importStatus: true,
    countryOfOrigin: 'Multan Mandi Breeding Center',
    milkYieldLitersPerDay: 16,
    pregnancyStatus: 'lactating',
    healthScore: 94,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    isListedForSale: true,
    askingPrice: 355000,
    sellerName: 'Mian Tariq Hassan',
    sellerPhone: '0301-7788990',
    sellerCity: 'Multan',
    saleDescription: '2nd Lactation, highly dociled, verified milk capacity 16 liters/day. Complete vaccination records.',
    marketRateBenchmarkPKR: 350000,
    createdAt: '2026-07-20',
    updatedAt: '2026-08-01',
  },
  {
    id: 'mkt_002',
    ownerId: 'mkt_owner_02',
    tagId: 'MND-9904',
    name: 'Nili Ravi Queen Buffalo (نیلی شہزادی)',
    species: 'buffalo',
    breed: 'Pure Nili Ravi Okara Breed',
    gender: 'female',
    ageMonths: 42,
    weightKg: 620,
    dob: '2022-11-15',
    purchasePrice: 430000,
    currentMarketValue: 510000,
    marketValueChangePercent: 18.6,
    importStatus: true,
    countryOfOrigin: 'Okara Buffalo Genetics',
    milkYieldLitersPerDay: 19,
    pregnancyStatus: 'lactating',
    healthScore: 92,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    isListedForSale: true,
    askingPrice: 500000,
    sellerName: 'Chaudhry Waseem Akram',
    sellerPhone: '0300-4455667',
    sellerCity: 'Sahiwal Mandi',
    saleDescription: 'Top fat percentage (7.2% Fat). Quiet milking temperament, 19 liters daily.',
    marketRateBenchmarkPKR: 495000,
    createdAt: '2026-07-25',
    updatedAt: '2026-08-02',
  },
  {
    id: 'mkt_003',
    ownerId: 'mkt_owner_03',
    tagId: 'MND-3310',
    name: 'Makra Kamori Goat (مکرا گلابی گوٹ)',
    species: 'goat',
    breed: 'Gulabi Kamori Pedigree',
    gender: 'female',
    ageMonths: 14,
    weightKg: 58,
    dob: '2025-05-10',
    purchasePrice: 85000,
    currentMarketValue: 125000,
    marketValueChangePercent: 47.0,
    importStatus: false,
    milkYieldLitersPerDay: 3.5,
    pregnancyStatus: 'pregnant',
    pregnancyMonths: 3,
    healthScore: 95,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    isListedForSale: true,
    askingPrice: 120000,
    sellerName: 'Haji Gulzar Ahmed',
    sellerPhone: '0302-3344556',
    sellerCity: 'Hyderabad',
    saleDescription: '3 months pregnant with Kamori prize stud. Long ears (24 inches), pure pink hide.',
    marketRateBenchmarkPKR: 118000,
    createdAt: '2026-07-28',
    updatedAt: '2026-08-03',
  },
  {
    id: 'mkt_004',
    ownerId: 'mkt_owner_04',
    tagId: 'MND-5120',
    name: 'Cholistani Camel (صحرا کا رتن)',
    species: 'camel',
    breed: 'Cholistani Mahra Camel',
    gender: 'male',
    ageMonths: 36,
    weightKg: 520,
    dob: '2023-08-01',
    purchasePrice: 380000,
    currentMarketValue: 460000,
    marketValueChangePercent: 21.0,
    importStatus: false,
    milkYieldLitersPerDay: 0,
    pregnancyStatus: 'none',
    healthScore: 90,
    healthStatus: 'excellent',
    photos: [
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800'
    ],
    videos: [],
    vaccinationHistory: [],
    medicalHistory: [],
    scanJournal: [],
    auditLogs: [],
    ownershipHistory: [],
    isListedForSale: true,
    askingPrice: 450000,
    sellerName: 'Sardar Rahim Yar Khan',
    sellerPhone: '0306-1122334',
    sellerCity: 'Bahawalpur',
    saleDescription: 'Strong Cholistani riding & load camel. Healthy joints, docile temperament.',
    marketRateBenchmarkPKR: 445000,
    createdAt: '2026-07-30',
    updatedAt: '2026-08-04',
  }
];

export const initialVets: VetDoctor[] = [
  {
    id: 'vet_001',
    name: 'Dr. Tariq Mahmood',
    specialty: 'Senior Livestock Specialist & Surgeon',
    qualifications: 'DVM, M.Phil (UVAS Lahore)',
    experienceYears: 14,
    phone: '0301-7654321',
    clinicAddress: 'Civil Veterinary Hospital, Sahiwal City',
    city: 'Sahiwal',
    distanceKm: 4.2,
    rating: 4.9,
    consultationFeePKR: 1000,
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: true,
  },
  {
    id: 'vet_002',
    name: 'Dr. Sanaullah Khan',
    specialty: 'Bovine Reproduction & Artificial Insemination',
    qualifications: 'DVM, MSc (Livestock Breeding)',
    experienceYears: 9,
    phone: '0333-8899001',
    clinicAddress: 'Kisan Cattle Care Clinic, G.T Road Sahiwal',
    city: 'Sahiwal',
    distanceKm: 7.8,
    rating: 4.8,
    consultationFeePKR: 800,
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: true,
  },
  {
    id: 'vet_003',
    name: 'Dr. Faiza Malik',
    specialty: 'Veterinary Pathologist & Poultry Specialist',
    qualifications: 'DVM, PhD (Veterinary Medicine)',
    experienceYears: 11,
    phone: '0302-5544332',
    clinicAddress: 'District Livestock Diagnostic Lab, Chichawatni',
    city: 'Chichawatni',
    distanceKm: 18.5,
    rating: 4.9,
    consultationFeePKR: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: false,
  }
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt_101',
    farmerId: 'usr_001',
    vetId: 'vet_001',
    vetName: 'Dr. Tariq Mahmood',
    animalId: 'anm_001',
    animalName: 'Sahiwal Queen',
    date: '2026-08-08',
    timeSlot: '11:00 AM',
    type: 'video',
    status: 'confirmed',
    reason: 'Monthly pregnancy check-up & milk yield consultation',
  }
];

export const initialExpenses: FarmExpense[] = [
  {
    id: 'exp_001',
    date: '2026-08-01',
    category: 'feed',
    amountPKR: 28500,
    description: 'Green Fodder (Berseem/Lucerne) & Wheat Straw (Bhoosa) - 50 Maunds',
  },
  {
    id: 'exp_002',
    date: '2026-08-02',
    category: 'feed',
    amountPKR: 18000,
    description: 'High-Protein Dairy Concentrate Feed (Vanda Wana) - 10 Bags',
  },
  {
    id: 'exp_003',
    date: '2026-07-28',
    category: 'medicine',
    amountPKR: 3500,
    description: 'De-worming solution & Udder Teat Dip disinfectant',
  },
  {
    id: 'exp_004',
    date: '2026-07-20',
    category: 'vet',
    amountPKR: 2000,
    description: 'Doctor consultation fee for Hoof treatment (Sahiwal Sultan)',
  }
];

export const initialOutbreaks: OutbreakReport[] = [
  {
    id: 'out_001',
    district: 'Sahiwal',
    region: 'Chichawatni & Harappa Sector',
    diseaseName: 'Lumpy Skin Disease (لمپی سکن)',
    severity: 'moderate',
    affectedAnimalsCount: 24,
    coordinates: { lat: 30.6682, lng: 73.1114 },
    detectedDate: '2026-07-28',
    precautionsUrdu: 'مچھروں اور مکھیوں کا خاتمہ کریں، متاثرہ جانور فوراً الگ رکھیں، اینٹی بائیوٹک اور ویکسینیشن فوری کروائیں۔',
    precautionsEn: 'Eliminate flies & mosquitoes, quarantine sick cattle, administer booster vaccines.',
    status: 'active',
  },
  {
    id: 'out_002',
    district: 'Okara',
    region: 'Renala Khurd Belt',
    diseaseName: 'Foot and Mouth Disease (منہ کھُر)',
    severity: 'severe',
    affectedAnimalsCount: 52,
    coordinates: { lat: 30.8122, lng: 73.4473 },
    detectedDate: '2026-07-20',
    precautionsUrdu: 'فارم پر بیرونی افراد اور گاڑیوں کا داخلہ بند کریں، پوٹاشیم پرمینگنیٹ (لال دوا) سے برتن دھوئیں اور منہ دھوئیں۔',
    precautionsEn: 'Restrict farm visitors, wash animal mouths with Potassium Permanganate solution daily.',
    status: 'active',
  }
];

export const offlineKnowledgeBase: OfflineKnowledgeItem[] = [
  {
    diseaseNameUrdu: 'لمپی سکن بیماری (Lumpy Skin Disease)',
    diseaseNameEn: 'Lumpy Skin Disease (LSD)',
    symptoms: [
      'جسم پر سخت گول دانے یا گلٹیاں بننا',
      'تیز بخار (104-106 ڈگری)',
      'آنکھوں اور ناک سے پانی بہنا',
      'ٹانگوں میں سوجن اور لنگڑاہٹ'
    ],
    firstAidSteps: [
      'متاثرہ جانور کو فوری الگ باقی مویشیوں سے دور رکھیں',
      'بخار کم کرنے کے لیے ٹھنڈا پانی سر اور پیٹھ پر ڈالیں',
      'دانوں پر ڈیٹول یا پوویڈین مرہم لگائیں',
      'مکھیوں سے بچاؤ کے لیے سپرے کریں'
    ],
    commonMedicines: [
      'Meloxicam / Paracetamol Injection (بخار اور درد کے لیے)',
      'Oxytetracycline / Penicillin (انفیکشن روکنے کے لیے)',
      'Multivitamin & Liver Tonic'
    ],
    preventionGuidance: 'سال میں ایک بار LSD کی ویکسین لازمی لگوائیں اور باڑے میں مکھی مچھر کا سپرے کروائیں۔'
  },
  {
    diseaseNameUrdu: 'منہ کھُر بیماری (Foot and Mouth Disease)',
    diseaseNameEn: 'Foot and Mouth Disease (FMD)',
    symptoms: [
      'منہ کے اندر، زبان اور مسوڑھوں پر چھالے',
      'منہ سے لمبی لیس دار جھاگ گرنا',
      'کھُروں (سم) کے درمیان زخم اور شدید لنگڑاہٹ',
      'دودھ کی پیداوار میں اچانک شدید کمی'
    ],
    firstAidSteps: [
      'منہ کو لال دوا (Potassium Permanganate) کے ہلکے محلول سے دھوئیں',
      'سموں پر زنک آکسائیڈ یا کاپر سلفیٹ کا پیسٹ لگائیں',
      'جانور کو نرم دلیہ، سوجی یا بھیگا ہوا ونڈا کھلائیں'
    ],
    commonMedicines: [
      'Anti-inflammatory Injections (Flunixin Meglumine)',
      'Antiseptic Mouth Wash',
      'Broad-spectrum Antibiotics for secondary infection'
    ],
    preventionGuidance: 'ہر 6 ماہ بعد FMD بائی ویلنٹ یا ٹرائی ویلنٹ ویکسین لگوائیں۔'
  },
  {
    diseaseNameUrdu: 'مستائٹس / تھنوں کی سوجن (Mastitis)',
    diseaseNameEn: 'Mastitis (Udder Infection)',
    symptoms: [
      'تھن یا ہوانہ کا سرخ، گرم اور دردناک ہونا',
      'دودھ میں پھٹکیاں، خون یا پیپ آنا',
      'جانور کا تھن کو ہاتھ نہ لگانے دینا'
    ],
    firstAidSteps: [
      'تھن کو نیم گرم پانی اور نمک سے سیکیں',
      'متاثرہ تھن سے پورا خراب دودھ باہر نکال کر تلف کر دیں',
      'دودھ دوہنے سے پہلے اور بعد میں تھنوں کو اینٹی سیپٹک ڈِپ کریں'
    ],
    commonMedicines: [
      'Intramammary Infusion Tubes (Teat Injection)',
      'Systemic Antibiotics (Amoxicillin/Ceftiofur)',
      'Anti-swelling Antiphlogistine paste'
    ],
    preventionGuidance: 'دودھ نکالنے والی جگہ بالکل صاف اور خشک رکھیں۔ دودھ دوہنے کے فوراً بعد جانور کو لیٹنے نہ دیں، 30 منٹ چارہ کھلائیں۔'
  },
  {
    diseaseNameUrdu: 'گل گھوٹو (Hemorrhagic Septicemia)',
    diseaseNameEn: 'Hemorrhagic Septicemia (HS)',
    symptoms: [
      'گردن اور جھالر میں شدید دردناک سوجن',
      'سانس لینے میں شدید دشواری اور غرغراہٹ کی آواز',
      'تیز بخار اور آنکھیں سرخ ہونا'
    ],
    firstAidSteps: [
      'فوری ہنگامی طور پر ویٹرنری ڈاکٹر کو بلائیں',
      'جانور کو کھلی ہوا دار جگہ پر رکھیں',
      'گردن کی سوجن پر ٹھنڈی پٹیاں رکھیں'
    ],
    commonMedicines: [
      'High-dose Sulfadimidine Injection',
      'Ceftiofur Sodium Injection',
      'Dexamethasone / Anti-inflammatory'
    ],
    preventionGuidance: 'برسات کے موسم سے پہلے (مئی - جون) گل گھوٹو کی ویکسین لازمی لگوائیں۔'
  }
];

export const initialDairyProducts: DairyProduct[] = [
  {
    id: 'prod-1',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص گائے کا تازہ دودھ (Fresh Pure Cow Milk)',
    nameEn: 'Fresh Pure Cow Milk',
    nameUr: 'خالص گائے کا تازہ دودھ',
    category: 'milk',
    categoryEn: 'Milk',
    price: 220,
    pricePKR: 220,
    unit: 'Liter',
    unitUr: 'لیٹر',
    stock: 50,
    dailyCapacity: '50 لیٹر روزانہ',
    isOrganic: true,
    inStock: true,
    rating: 4.9,
    description: '100% pure organic Sahiwal cow milk, fresh from morning milking.',
    descriptionEn: '100% pure organic Sahiwal cow milk, fresh from morning milking.',
    descriptionUr: 'خالص ساہیوال گائے کا تازہ آرگینک دودھ۔ بغیر کسی ملاوٹ کے۔',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-05'
  },
  {
    id: 'prod-2',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص نیلی راوی بھینس کا گاڑھا دہی (Pure Thick Buffalo Yogurt)',
    nameEn: 'Pure Thick Buffalo Yogurt',
    nameUr: 'خالص نیلی راوی بھینس کا گاڑھا دہی',
    category: 'yogurt',
    categoryEn: 'Yogurt',
    price: 260,
    pricePKR: 260,
    unit: 'Kg',
    unitUr: 'کلو',
    stock: 30,
    dailyCapacity: '30 کلو روزانہ',
    isOrganic: true,
    inStock: true,
    rating: 4.8,
    description: 'Traditional clay-pot set thick buffalo milk yogurt.',
    descriptionEn: 'Traditional clay-pot set thick buffalo milk yogurt.',
    descriptionUr: 'روایتی مٹی کی کونڈی میں جما ہوا میٹھا اور گاڑھا دہی۔',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-05'
  },
  {
    id: 'prod-3',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص چاٹی کا دیسی گھی (Pure Traditional Desi Ghee)',
    nameEn: 'Pure Traditional Desi Ghee',
    nameUr: 'خالص چاٹی کا دیسی گھی',
    category: 'ghee',
    categoryEn: 'Desi Ghee',
    price: 2400,
    pricePKR: 2400,
    unit: 'Kg',
    unitUr: 'کلو',
    stock: 15,
    dailyCapacity: '15 کلو دستیاب',
    isOrganic: true,
    inStock: true,
    rating: 5.0,
    description: 'Slow-cooked traditional organic butter oil / pure ghee.',
    descriptionEn: 'Slow-cooked traditional organic butter oil / pure ghee.',
    descriptionUr: 'دیسی مکھن کو ہلکی آنچ پر پکا کر تیار کردہ 100% خالص اور خوشبودار دیسی گھی۔',
    imageUrl: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-04'
  },
  {
    id: 'prod-4',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'تازو خالص وائٹ مکھن (Organic Fresh White Butter)',
    nameEn: 'Organic Fresh White Butter',
    nameUr: 'تازو خالص وائٹ مکھن',
    category: 'butter',
    categoryEn: 'Butter',
    price: 1800,
    pricePKR: 1800,
    unit: 'Kg',
    unitUr: 'کلو',
    stock: 20,
    dailyCapacity: '20 کلو روزانہ',
    isOrganic: true,
    inStock: true,
    rating: 4.9,
    description: 'Freshly churned cultured white butter from pure curd.',
    descriptionEn: 'Freshly churned cultured white butter from pure curd.',
    descriptionUr: 'تازہ دہی کی چاٹی سے بنا ہوا بغیر نمک کا خالص مکھن۔',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-05'
  },
  {
    id: 'prod-5',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص دودھ کا کھویا (Fresh Mawa / Khoya)',
    nameEn: 'Fresh Mawa / Khoya',
    nameUr: 'خالص دودھ کا کھویا',
    category: 'khoya',
    categoryEn: 'Khoya',
    price: 1200,
    pricePKR: 1200,
    unit: 'Kg',
    unitUr: 'کلو',
    stock: 10,
    dailyCapacity: '10 کلو فرمائش پر',
    isOrganic: true,
    inStock: true,
    rating: 4.7,
    description: 'Unsweetened condensed whole milk solids for sweets & tea.',
    descriptionEn: 'Unsweetened condensed whole milk solids for sweets & tea.',
    descriptionUr: 'خالص دودھ کو کڑاہی میں کاڑھ کر تیار کردہ بغیر چینی کا کھویا۔',
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-03'
  },
  {
    id: 'prod-6',
    sellerId: 'usr_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'مکھن والی مٹھائی اور نمکین لسی (Fresh Sweet Farm Lassi)',
    nameEn: 'Fresh Sweet Farm Lassi',
    nameUr: 'مکھن والی مٹھائی اور نمکین لسی',
    category: 'lassi',
    categoryEn: 'Lassi',
    price: 120,
    pricePKR: 120,
    unit: 'Liter',
    unitUr: 'لیٹر',
    stock: 40,
    dailyCapacity: '40 لیٹر روزانہ',
    isOrganic: true,
    inStock: true,
    rating: 4.8,
    description: 'Chilled authentic farm churned buttermilk with butter top.',
    descriptionEn: 'Chilled authentic farm churned buttermilk with butter top.',
    descriptionUr: 'مکھن کے پیڑے کے ساتھ ٹھنڈی اور مزیدار مٹی کے گلاس والی لسی۔',
    imageUrl: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?auto=format&fit=crop&q=80&w=800',
    updatedAt: '2026-08-05'
  }
];

export const initialAdminUsers: AdminUserItem[] = [
  {
    id: 'usr_001',
    name: 'Chaudhry Ahmed Ali',
    email: 'ahmed.farm@kisandost.ai',
    phone: '0300-1234567',
    role: 'super_admin',
    status: 'active',
    registrationDate: '2026-01-10',
    lastLogin: '2026-08-21 09:45 AM',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    location: 'Chak 88/9-L, Sahiwal, Punjab',
    district: 'Sahiwal',
    language: 'ur',
    isVerified: true,
    notes: 'Primary Master Farm Administrator and Certified Livestock Breeder.',
    totalRecordsCount: 28,
    totalAIRequestsCount: 84
  },
  {
    id: 'usr_002',
    name: 'Dr. Tariq Mahmood (Vet)',
    email: 'dr.tariq@kisandost.ai',
    phone: '0300-7654321',
    role: 'moderator',
    status: 'active',
    registrationDate: '2026-02-14',
    lastLogin: '2026-08-20 04:30 PM',
    farmName: 'Sahiwal Animal Hospital & Clinic',
    location: 'Civil Lines, Sahiwal',
    district: 'Sahiwal',
    language: 'ur',
    isVerified: true,
    notes: 'District Veterinary Officer & Health Reviewer.',
    totalRecordsCount: 42,
    totalAIRequestsCount: 120
  },
  {
    id: 'usr_003',
    name: 'Mian Bashir Gujjar',
    email: 'bashir.mandi@kisandost.ai',
    phone: '0312-4455667',
    role: 'admin',
    status: 'active',
    registrationDate: '2026-03-01',
    lastLogin: '2026-08-19 11:20 AM',
    farmName: 'Gujjar Dairy & Mandi Traders',
    location: 'Jhang Road, Faisalabad',
    district: 'Faisalabad',
    language: 'ur',
    isVerified: true,
    notes: 'Livestock Mandi Verified Trader & Auditor.',
    totalRecordsCount: 19,
    totalAIRequestsCount: 35
  },
  {
    id: 'usr_004',
    name: 'Haji Aslam Rasheed',
    email: 'aslam.dairy@gmail.com',
    phone: '0301-9876543',
    role: 'user',
    status: 'active',
    registrationDate: '2026-04-18',
    lastLogin: '2026-08-18 02:15 PM',
    farmName: 'Rasheed Organic Dairy',
    location: 'Multan Road, Sahiwal',
    district: 'Sahiwal',
    language: 'ur',
    isVerified: true,
    notes: 'Dairy retailer and customer buyer lead.',
    totalRecordsCount: 12,
    totalAIRequestsCount: 22
  },
  {
    id: 'usr_005',
    name: 'Rana Kamran Khan',
    email: 'kamran.rana@yahoo.com',
    phone: '0345-9988776',
    role: 'user',
    status: 'inactive',
    registrationDate: '2026-05-22',
    lastLogin: '2026-07-29 08:10 AM',
    farmName: 'Kamran Cattle Breeders',
    location: 'Depalpur Road, Okara',
    district: 'Okara',
    language: 'pb',
    isVerified: false,
    notes: 'Pending bio-security verification for animal listings.',
    totalRecordsCount: 4,
    totalAIRequestsCount: 9
  },
  {
    id: 'usr_006',
    name: 'Malik Zafar Iqbal',
    email: 'malik.zafar@outlook.com',
    phone: '0333-1122334',
    role: 'user',
    status: 'suspended',
    registrationDate: '2026-06-05',
    lastLogin: '2026-07-15 01:00 PM',
    farmName: 'Zafar Feeds & Animals',
    location: 'Samundri, Faisalabad',
    district: 'Faisalabad',
    language: 'ur',
    isVerified: false,
    notes: 'Suspended due to unverified vaccine documents in Mandi.',
    totalRecordsCount: 2,
    totalAIRequestsCount: 5
  }
];

export const initialApplications: UserApplication[] = [
  {
    id: 'app_1001',
    userId: 'usr_004',
    applicantName: 'Haji Aslam Rasheed',
    applicantEmail: 'aslam.dairy@gmail.com',
    applicantPhone: '0301-9876543',
    applicationType: 'dairy_certification',
    submissionDate: '2026-08-19',
    status: 'pending',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    priority: 'high',
    documents: ['Lab_Milk_Purity_Test.pdf', 'Chiller_Hygiene_Inspection.pdf'],
    adminNotes: 'Awaiting lab testing report for somatic cell count & fat purity.',
    details: {
      farmName: 'Rasheed Organic Dairy',
      cnicOrRegistration: '35302-1234567-1',
      livestockCount: 35,
      dailyMilkCapacityLiters: 450,
      requestSummary: 'Application for Punjab Food Authority Certified Pure Dairy Tag.',
      district: 'Sahiwal',
      licenseGrade: 'Grade-A Organic'
    }
  },
  {
    id: 'app_1002',
    userId: 'usr_003',
    applicantName: 'Mian Bashir Gujjar',
    applicantEmail: 'bashir.mandi@kisandost.ai',
    applicantPhone: '0312-4455667',
    applicationType: 'mandi_seller',
    submissionDate: '2026-08-15',
    status: 'approved',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    decisionDate: '2026-08-16',
    priority: 'medium',
    documents: ['Trader_CNIC.pdf', 'Mandi_Association_License.pdf'],
    adminNotes: 'Verified trader with 15+ years experience. Badge approved.',
    details: {
      farmName: 'Gujjar Dairy & Mandi Traders',
      cnicOrRegistration: '33100-7654321-3',
      livestockCount: 60,
      requestSummary: 'Verified Mandi Master Seller with VIP Digital Badge.',
      district: 'Faisalabad',
      licenseGrade: 'Elite Trader'
    }
  },
  {
    id: 'app_1003',
    userId: 'usr_005',
    applicantName: 'Rana Kamran Khan',
    applicantEmail: 'kamran.rana@yahoo.com',
    applicantPhone: '0345-9988776',
    applicationType: 'farm_license',
    submissionDate: '2026-08-12',
    status: 'under_review',
    assignedAdmin: 'Dr. Tariq Mahmood',
    priority: 'urgent',
    documents: ['Land_Ownership_Fard.pdf', 'Vaccine_Ledger.pdf'],
    adminNotes: 'Field veterinary inspection scheduled for Friday.',
    details: {
      farmName: 'Kamran Cattle Breeders',
      cnicOrRegistration: '35301-9988776-5',
      livestockCount: 48,
      dailyMilkCapacityLiters: 320,
      requestSummary: 'Official Livestock Department Farm Registration License.',
      district: 'Okara',
      licenseGrade: 'Commercial Dairy'
    }
  },
  {
    id: 'app_1004',
    userId: 'usr_006',
    applicantName: 'Malik Zafar Iqbal',
    applicantEmail: 'malik.zafar@outlook.com',
    applicantPhone: '0333-1122334',
    applicationType: 'subsidy_grant',
    submissionDate: '2026-07-28',
    status: 'rejected',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    decisionDate: '2026-08-01',
    priority: 'low',
    documents: ['Feed_Purchase_Bills.pdf'],
    adminNotes: 'Rejected: Incomplete animal ear-tag vaccination logs.',
    details: {
      farmName: 'Zafar Feeds & Animals',
      cnicOrRegistration: '33102-5544332-9',
      livestockCount: 15,
      requestSummary: 'Green Silage & Feed Subsidy Program 2026.',
      district: 'Faisalabad',
      licenseGrade: 'Standard'
    }
  }
];

export const initialComplaints: UserComplaint[] = [
  {
    id: 'cmp_2001',
    userId: 'usr_004',
    userName: 'Haji Aslam Rasheed',
    userEmail: 'aslam.dairy@gmail.com',
    userPhone: '0301-9876543',
    category: 'delivery',
    title: 'Late Morning Milk Delivery Batch #KD-99',
    description: 'Fresh milk delivery was delayed by 2 hours due to transport route malfunction. Requested chilling compensation.',
    submissionDate: '2026-08-20',
    priority: 'high',
    status: 'in_progress',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    adminResponse: 'Delivery team dispatched replacement batch with insulated vehicle. Route updated.',
    attachments: ['delivery_time_slip.png']
  },
  {
    id: 'cmp_2002',
    userId: 'usr_005',
    userName: 'Rana Kamran Khan',
    userEmail: 'kamran.rana@yahoo.com',
    userPhone: '0345-9988776',
    category: 'pricing',
    title: 'Discrepancy in Mandi Market Benchmark Rate',
    description: 'The Sahiwal Cow benchmark price displayed PKR 340,000 whereas local market traded at PKR 365,000.',
    submissionDate: '2026-08-16',
    priority: 'medium',
    status: 'resolved',
    assignedAdmin: 'Mian Bashir Gujjar',
    adminResponse: 'Algorithm price feed refreshed with live Sahiwal Mandi Tuesday auction prices.',
    resolvedDate: '2026-08-17'
  },
  {
    id: 'cmp_2003',
    userId: 'usr_006',
    userName: 'Malik Zafar Iqbal',
    userEmail: 'malik.zafar@outlook.com',
    userPhone: '0333-1122334',
    category: 'technical_bug',
    title: 'QR Tag Scan camera timeout in low light',
    description: 'Ear-tag scanner takes over 5 seconds to recognize brass tags in shaded barn stalls.',
    submissionDate: '2026-08-10',
    priority: 'low',
    status: 'under_review',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    adminResponse: 'High-contrast QR recognition shader patch is in development.'
  },
  {
    id: 'cmp_2004',
    userId: 'usr_004',
    userName: 'Haji Aslam Rasheed',
    userEmail: 'aslam.dairy@gmail.com',
    userPhone: '0301-9876543',
    category: 'milk_quality',
    title: 'Desi Ghee Aroma and Granulation Quality Inconsistency',
    description: 'Last week batch of Desi Ghee had lower grain density compared to standard Danedar batch.',
    submissionDate: '2026-08-04',
    priority: 'urgent',
    status: 'resolved',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    adminResponse: 'Replaced with 100% slow-simmered brass pot ghee. Farmer granted 15% discount voucher.',
    resolvedDate: '2026-08-05'
  }
];

export const initialSystemReports: SystemReport[] = [
  {
    id: 'rep_3001',
    userId: 'usr_002',
    userName: 'Dr. Tariq Mahmood (Vet)',
    reportType: 'outbreak_alert',
    title: 'Lumpy Skin Disease (LSD) Vector Cluster Alert',
    summary: 'Detected 14 localized cases along Chichawatni border belt. Prompt ring vaccination deployed.',
    date: '2026-08-18',
    status: 'investigating',
    priority: 'urgent',
    assignedAdmin: 'Dr. Tariq Mahmood',
    affectedCount: 14,
    metrics: { district: 'Sahiwal / Chichawatni', containmentRadiusKm: 12, vaccinatedCount: 180 },
    adminNotes: 'Vaccination teams deployed to sectors 88-L and 92-L.'
  },
  {
    id: 'rep_3002',
    userId: 'usr_001',
    userName: 'Chaudhry Ahmed Ali',
    reportType: 'production_analytics',
    title: 'Quarterly Herd Milk Yield & Protein Optimization Report',
    summary: 'Average herd yield increased +14.2% following green Lucerne and bypass fat dietary adjustment.',
    date: '2026-08-15',
    status: 'reviewed',
    priority: 'medium',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    metrics: { totalDailyLiters: 114.5, avgFatPercent: 4.8, avgProteinPercent: 3.6 },
    adminNotes: 'Fodder formulation locked for autumn season.'
  },
  {
    id: 'rep_3003',
    userId: 'usr_003',
    userName: 'Mian Bashir Gujjar',
    reportType: 'financial_audit',
    title: 'Mandi Trading Liquidity & Purchase Yield Audit',
    summary: 'Overall livestock capital appreciation tracked at +18.4% across 8 breeding units.',
    date: '2026-08-01',
    status: 'resolved',
    priority: 'low',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    metrics: { totalHerdValuationPKR: 2680000, totalPurchasedPKR: 2260000, profitPKR: 420000 }
  },
  {
    id: 'rep_3004',
    userId: 'usr_001',
    userName: 'System AI Monitor',
    reportType: 'fraud_flag',
    title: 'Duplicate Ear Tag ID Check Security Flag',
    summary: 'Prevented duplicate tag creation KD-8842 on external unverified account.',
    date: '2026-07-29',
    status: 'resolved',
    priority: 'high',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    metrics: { flaggedTag: 'KD-8842', blockedIp: '182.185.120.44' },
    adminNotes: 'IP flagged and logged into security rules firewall.'
  }
];

export const initialNotifications: AdminNotification[] = [
  {
    id: 'notif_4001',
    title: '🚨 FMD Booster Vaccine Drive Scheduled for September',
    message: 'All cattle and buffalo owners in Sahiwal & Okara must complete Foot & Mouth Disease booster doses before Sep 15.',
    targetAudience: 'farmers',
    createdDate: '2026-08-20',
    scheduledDate: '2026-08-22',
    status: 'active',
    priority: 'alert',
    createdBy: 'Dr. Tariq Mahmood (Vet Officer)',
    recipientCount: 2850,
    readCount: 1940
  },
  {
    id: 'notif_4002',
    title: '🥛 Fresh Organic Desi Ghee New Batch Available',
    message: 'Pure traditional slow-churned Desi Ghee batch #14 is now live on the Kisan Dost Dairy Storefront.',
    targetAudience: 'dairy_buyers',
    createdDate: '2026-08-18',
    status: 'sent',
    priority: 'announcement',
    createdBy: 'Chaudhry Ahmed Ali',
    recipientCount: 1420,
    readCount: 1110
  },
  {
    id: 'notif_4003',
    title: '⚡ Gemini 3.7 AI Diagnostic Engine Online',
    message: 'Enhanced veterinary disease vision scanner and Punjabi voice diagnosis are now fully enabled for all members.',
    targetAudience: 'all',
    createdDate: '2026-08-15',
    status: 'sent',
    priority: 'info',
    createdBy: 'System Super Admin',
    recipientCount: 4500,
    readCount: 3890
  },
  {
    id: 'notif_4004',
    title: '⚠️ Heavy Monsoons Feed Storage Advisory',
    message: 'Protect dry Bhoosa (wheat straw) and silage bags from moisture to prevent mold and aflatoxin toxicity.',
    targetAudience: 'farmers',
    createdDate: '2026-08-10',
    status: 'expired',
    priority: 'warning',
    createdBy: 'Livestock Advisory Team',
    recipientCount: 3100,
    readCount: 2750
  }
];

export const initialMessageThreads: SupportMessageThread[] = [
  {
    id: 'msg_5001',
    userId: 'usr_004',
    userName: 'Haji Aslam Rasheed',
    userEmail: 'aslam.dairy@gmail.com',
    userPhone: '0301-9876543',
    subject: 'Bulk Weekly Milk Order Subscription (20 Liters/Day)',
    category: 'Commercial Dairy',
    status: 'open',
    unreadCount: 1,
    lastMessageDate: '2026-08-21 10:15 AM',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    messages: [
      {
        id: 'm_1',
        senderId: 'usr_004',
        senderName: 'Haji Aslam Rasheed',
        senderRole: 'user',
        message: 'السلام علیکم چوہدری صاحب! ہم اپنے ہوٹل کے لیے روزانہ 20 لیٹر خالص گائے کے دودھ کا مستقل کنٹریکٹ کرنا چاہتے ہیں۔ ریٹ اور صبح کی ٹائمنگ بتا دیں۔',
        timestamp: '2026-08-21 09:30 AM'
      },
      {
        id: 'm_2',
        senderId: 'usr_001',
        senderName: 'Chaudhry Ahmed Ali (Admin)',
        senderRole: 'admin',
        message: 'وعلیکم السلام حاجی صاحب! ہمارے پاس صبح 6:30 بجے خالص چلڈ دودھ 215 روپے فی لیٹر ہول سیل ریٹ پر دستیاب ہے۔ ہم کنٹریکٹ فارم بھجواتے ہیں۔',
        timestamp: '2026-08-21 09:50 AM'
      },
      {
        id: 'm_3',
        senderId: 'usr_004',
        senderName: 'Haji Aslam Rasheed',
        senderRole: 'user',
        message: 'بہترین! فارم پر کل صبح سیمپل کی فراہمی یقینی بنا دیں۔ شکریہ۔',
        timestamp: '2026-08-21 10:15 AM'
      }
    ]
  },
  {
    id: 'msg_5002',
    userId: 'usr_005',
    userName: 'Rana Kamran Khan',
    userEmail: 'kamran.rana@yahoo.com',
    userPhone: '0345-9988776',
    subject: 'Assistance regarding Sahiwal Bull Bloodline Pedigree',
    category: 'Livestock Breeding',
    status: 'in_progress',
    unreadCount: 0,
    lastMessageDate: '2026-08-19 03:40 PM',
    assignedAdmin: 'Dr. Tariq Mahmood',
    messages: [
      {
        id: 'm_4',
        senderId: 'usr_005',
        senderName: 'Rana Kamran Khan',
        senderRole: 'user',
        message: 'ڈاکٹر صاحب! کیا آپ سوہنی گائے کے سائر (Sire) کا سیمن آرٹیفیشل انسیمینیشن کے لیے دستیاب کر سکتے ہیں؟',
        timestamp: '2026-08-19 02:00 PM'
      },
      {
        id: 'm_5',
        senderId: 'usr_002',
        senderName: 'Dr. Tariq Mahmood (Vet)',
        senderRole: 'admin',
        message: 'جی رانا صاحب! ساہیوال چیمپئن کنگ-01 کی ڈوزز سیمن بینک ساہیوال میں رجسٹرڈ ہیں۔ آپ کل کلینک وزٹ کر سکتے ہیں۔',
        timestamp: '2026-08-19 03:40 PM'
      }
    ]
  },
  {
    id: 'msg_5003',
    userId: 'usr_003',
    userName: 'Mian Bashir Gujjar',
    userEmail: 'bashir.mandi@kisandost.ai',
    userPhone: '0312-4455667',
    subject: 'Mandi Animal Listing Verification Completed',
    category: 'Mandi Trading',
    status: 'resolved',
    unreadCount: 0,
    lastMessageDate: '2026-08-17 11:00 AM',
    assignedAdmin: 'Chaudhry Ahmed Ali',
    messages: [
      {
        id: 'm_6',
        senderId: 'usr_003',
        senderName: 'Mian Bashir Gujjar',
        senderRole: 'user',
        message: 'منڈی میں لسٹ کی گئی نیلی راوی بھینس کی قیمت اور تصویریں اپ ڈیٹ کر دی گئی ہیں۔',
        timestamp: '2026-08-17 10:20 AM'
      },
      {
        id: 'm_7',
        senderId: 'usr_001',
        senderName: 'Chaudhry Ahmed Ali',
        senderRole: 'admin',
        message: 'منڈی لسٹنگ تصدیق شدہ اور لائیو کر دی گئی ہے۔',
        timestamp: '2026-08-17 11:00 AM'
      }
    ]
  }
];

export const initialAIActivityLogs: AIActivityLog[] = [
  {
    id: 'ai_6001',
    userId: 'usr_001',
    userName: 'Chaudhry Ahmed Ali',
    dateTime: '2026-08-21 08:30 AM',
    queryType: 'disease_scan',
    userQuery: 'Ear lesions and high fever inspection on Sahiwal Queen',
    aiResponsePreview: 'Detected: Mild Mastitis / Udder Swelling (94% confidence). Recommended: Mammitis teat dip and Penicillin course.',
    modelUsed: 'gemini-3.7-flash (Vision)',
    status: 'success',
    processingTimeMs: 1420,
    tokenCount: 680,
    feedbackScore: 5
  },
  {
    id: 'ai_6002',
    userId: 'usr_004',
    userName: 'Haji Aslam Rasheed',
    dateTime: '2026-08-20 02:15 PM',
    queryType: 'doctor_assistant',
    userQuery: 'بھینس کو افارہ ہو گیا ہے اور پیٹ پھول رہا ہے، فوری دیسی علاج بتائیں',
    aiResponsePreview: 'فوری اقدامات: 200 ملی لیٹر سرسوں کا تیل اور 50 گرام میٹھا سوڈا دیں۔ جانور کو آہستہ آہستہ چلائیں۔',
    modelUsed: 'gemini-3.7-flash (Urdu Voice Doctor)',
    status: 'success',
    processingTimeMs: 1180,
    tokenCount: 490,
    feedbackScore: 5
  },
  {
    id: 'ai_6003',
    userId: 'usr_002',
    userName: 'Dr. Tariq Mahmood',
    dateTime: '2026-08-20 11:45 AM',
    queryType: 'nutrition_plan',
    userQuery: 'Generate high-protein lactation ration for 480kg Sahiwal Cow yielding 18 liters milk',
    aiResponsePreview: 'Daily Formulation: 35kg Berseem + 5kg Wheat Straw + 4.5kg 18% Dairy Vanda. Total cost: PKR 420/day.',
    modelUsed: 'gemini-3.7-flash (Structured Schema)',
    status: 'success',
    processingTimeMs: 950,
    tokenCount: 520,
    feedbackScore: 5
  },
  {
    id: 'ai_6004',
    userId: 'usr_005',
    userName: 'Rana Kamran Khan',
    dateTime: '2026-08-19 04:10 PM',
    queryType: 'digital_twin',
    userQuery: 'Calculate 6-month value projection and heat stress vulnerability index',
    aiResponsePreview: 'Overall Risk Score: 18/100. Projected 6M Market Value: PKR 385,000 (+15.2% appreciation).',
    modelUsed: 'gemini-3.7-flash (Digital Twin Predictor)',
    status: 'success',
    processingTimeMs: 1320,
    tokenCount: 410,
    feedbackScore: 4
  },
  {
    id: 'ai_6005',
    userId: 'usr_001',
    userName: 'Chaudhry Ahmed Ali',
    dateTime: '2026-08-18 09:00 AM',
    queryType: 'medicine_scan',
    userQuery: 'Scan label of Oxytetracycline 20% LA antibiotic bottle',
    aiResponsePreview: 'Authentic: True. Category: Broad-Spectrum Antibiotic. Milk withdrawal: 7 days, Meat: 21 days.',
    modelUsed: 'gemini-3.7-flash (Vision OCR)',
    status: 'success',
    processingTimeMs: 1540,
    tokenCount: 710,
    feedbackScore: 5
  }
];

export const initialAdminAuditLogs: AdminAuditLogEntry[] = [
  {
    id: 'log_7001',
    adminId: 'usr_001',
    adminName: 'Chaudhry Ahmed Ali',
    adminRole: 'super_admin',
    action: 'USER_ROLE_UPDATED',
    targetModule: 'users',
    targetUserId: 'usr_002',
    previousValue: 'user',
    newValue: 'moderator',
    ipAddress: '182.185.120.10',
    deviceInfo: 'Chrome 128 (macOS)',
    timestamp: '2026-08-21 09:15 AM',
    status: 'success'
  },
  {
    id: 'log_7002',
    adminId: 'usr_001',
    adminName: 'Chaudhry Ahmed Ali',
    adminRole: 'super_admin',
    action: 'APPLICATION_APPROVED',
    targetModule: 'applications',
    targetRecordId: 'app_1002',
    previousValue: 'pending',
    newValue: 'approved',
    ipAddress: '182.185.120.10',
    deviceInfo: 'Chrome 128 (macOS)',
    timestamp: '2026-08-16 02:40 PM',
    status: 'success'
  },
  {
    id: 'log_7003',
    adminId: 'usr_001',
    adminName: 'Chaudhry Ahmed Ali',
    adminRole: 'super_admin',
    action: 'DAIRY_PRICE_MODIFIED',
    targetModule: 'dairy',
    targetRecordId: 'dry_001',
    previousValue: 'PKR 210',
    newValue: 'PKR 220',
    ipAddress: '182.185.120.10',
    deviceInfo: 'Chrome 128 (macOS)',
    timestamp: '2026-08-15 11:10 AM',
    status: 'success'
  },
  {
    id: 'log_7004',
    adminId: 'usr_002',
    adminName: 'Dr. Tariq Mahmood',
    adminRole: 'moderator',
    action: 'COMPLAINT_RESOLVED',
    targetModule: 'complaints',
    targetRecordId: 'cmp_2002',
    previousValue: 'in_progress',
    newValue: 'resolved',
    ipAddress: '39.40.155.88',
    deviceInfo: 'Safari (iOS iPhone 15)',
    timestamp: '2026-08-17 04:20 PM',
    status: 'success'
  },
  {
    id: 'log_7005',
    adminId: 'usr_001',
    adminName: 'Chaudhry Ahmed Ali',
    adminRole: 'super_admin',
    action: 'NOTIFICATION_BROADCAST',
    targetModule: 'notifications',
    targetRecordId: 'notif_4001',
    previousValue: 'draft',
    newValue: 'active (sent to 2850 farmers)',
    ipAddress: '182.185.120.10',
    deviceInfo: 'Chrome 128 (macOS)',
    timestamp: '2026-08-20 08:00 AM',
    status: 'success'
  },
  {
    id: 'log_7006',
    adminId: 'usr_001',
    adminName: 'Chaudhry Ahmed Ali',
    adminRole: 'super_admin',
    action: 'SECURITY_ACCOUNT_SUSPENDED',
    targetModule: 'users',
    targetUserId: 'usr_006',
    previousValue: 'active',
    newValue: 'suspended (fraudulent tag flags)',
    ipAddress: '182.185.120.10',
    deviceInfo: 'Chrome 128 (macOS)',
    timestamp: '2026-07-29 02:30 PM',
    status: 'success'
  }
];

export const initialAdminSystemSettings: AdminSystemSettings = {
  maintenanceMode: false,
  allowNewRegistrations: true,
  defaultUserRole: 'user',
  geminiModel: 'gemini-3.7-flash',
  enableAIImageDiagnosis: true,
  enableLiveOfflineSync: true,
  maxDailyAIRequestsPerUser: 100,
  autoApproveLowRiskApplications: false,
  backupSchedule: 'daily_0200_gmt',
  superAdminEmails: ['ahmed.farm@kisandost.ai', 'admin@kisandost.ai']
};


