// lib/models/seed_data.dart
// Ported from src/lib/mockData.ts

import 'animal.dart';
import 'dairy.dart';
import 'enums.dart';
import 'expense.dart';
import 'offline_knowledge.dart';
import 'outbreak.dart';
import 'user.dart';
import 'vet_appointment.dart';

final User initialUser = User(
  id: 'usr_001',
  name: 'Chaudhry Ahmed Ali',
  phone: '0300-1234567',
  email: 'ahmed.farm@kisandost.ai',
  farmName: 'Al-Madina Dairy & Cattle Farm',
  location: 'Chak 88/9-L, Sahiwal, Punjab',
  district: 'Sahiwal',
  language: Language.ur,
  isPremium: true,
  hasCompletedOnboarding: false,
  createdAt: '2026-01-10T10:00:00Z',
);

final List<Animal> initialAnimals = [
  Animal(
    id: 'anm_001',
    ownerId: 'usr_001',
    tagId: 'KD-8842',
    name: 'Sahiwal Queen (سوہنی)',
    species: Species.cow,
    breed: 'Pure Sahiwal Breed',
    gender: Gender.female,
    ageMonths: 48,
    weightKg: 485,
    dob: '2022-08-15',
    purchasePrice: 320000,
    currentMarketValue: 385000,
    marketValueChangePercent: 20.3,
    importStatus: false,
    bloodline: 'Royal Sahiwal Champion Line',
    sireInfo: 'Sahiwal Stud King-01',
    damInfo: 'Sahiwal Beauty-88',
    pregnancyStatus: PregnancyStatus.lactating,
    pregnancyMonths: 0,
    milkYieldLitersPerDay: 18.5,
    healthScore: 92,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800',
    ],
    vaccinationHistory: [
      VaccinationRecord(
        id: 'vac_101',
        animalId: 'anm_001',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth Disease',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: VaccinationStatus.completed,
      ),
      VaccinationRecord(
        id: 'vac_102',
        animalId: 'anm_001',
        vaccineName: 'LSD (لمپی سکن)',
        diseaseTarget: 'Lumpy Skin Disease',
        dateGiven: '2026-01-15',
        nextDueDate: '2027-01-15',
        administeredBy: 'Dr. Tariq Mahmood',
        status: VaccinationStatus.completed,
      ),
      VaccinationRecord(
        id: 'vac_103',
        animalId: 'anm_001',
        vaccineName: 'HS (گل گھوٹو)',
        diseaseTarget: 'Hemorrhagic Septicemia',
        dateGiven: '2025-11-20',
        nextDueDate: '2026-08-20',
        administeredBy: 'Dr. Sanaullah',
        status: VaccinationStatus.scheduled,
      ),
    ],
    medicalHistory: [
      MedicalRecord(
        id: 'med_001',
        animalId: 'anm_001',
        date: '2026-05-12',
        diagnosis: 'Mild Udder Swelling (مستائٹس ابتداء)',
        treatment: 'Intramammary Infusion & Anti-inflammatory',
        medicineGiven: 'Penicillin + Oxytetracycline',
        dosage: '10ml IM daily for 3 days',
        vetName: 'Dr. Tariq Mahmood',
        recoveryStatus: RecoveryStatus.cured,
      ),
    ],
    auditLogs: [
      AuditLog(
        id: 'aud_001',
        timestamp: '2026-07-01 10:15 AM',
        fieldChanged: 'Weight (kg)',
        oldValue: '470 kg',
        newValue: '485 kg',
        updatedBy: 'Chaudhry Ahmed Ali',
      ),
    ],
    ownershipHistory: [
      OwnershipRecord(
        id: 'own_001',
        date: '2023-01-10',
        sellerName: 'Sahiwal Government Breeding Farm',
        buyerName: 'Chaudhry Ahmed Ali',
        buyerPhone: '0300-1234567',
        salePrice: 320000,
        certificateNumber: 'PK-SAH-2023-8842',
      ),
    ],
    digitalLicenseNumber: 'PK-LIVESTOCK-8842-SAH',
    insuranceDetails: InsuranceDetail(
      policyNumber: 'Takaful-Live-90921',
      provider: 'Pak-Qatar Livestock Takaful',
      insuredValue: 350000,
      startDate: '2026-01-01',
      expiryDate: '2027-01-01',
      status: 'active',
    ),
    createdAt: '2023-01-10',
    updatedAt: '2026-07-01',
  ),
  Animal(
    id: 'anm_002',
    ownerId: 'usr_001',
    tagId: 'KD-9102',
    name: 'Nili Beauty (نیلی رانی)',
    species: Species.buffalo,
    breed: 'Nili-Ravi Pure Breed',
    gender: Gender.female,
    ageMonths: 36,
    weightKg: 580,
    dob: '2023-05-20',
    purchasePrice: 410000,
    currentMarketValue: 480000,
    marketValueChangePercent: 17.0,
    importStatus: false,
    bloodline: 'Nili-Ravi High-Milk Line',
    sireInfo: 'Kasur Champion Bull-99',
    damInfo: 'Okara Queen Buffalo',
    pregnancyStatus: PregnancyStatus.pregnant,
    pregnancyMonths: 6,
    milkYieldLitersPerDay: 16.0,
    healthScore: 89,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800',
    ],
    vaccinationHistory: [
      VaccinationRecord(
        id: 'vac_201',
        animalId: 'anm_002',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth Disease',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: VaccinationStatus.completed,
      ),
    ],
    digitalLicenseNumber: 'PK-LIVESTOCK-9102-NILI',
    createdAt: '2023-06-01',
    updatedAt: '2026-06-15',
  ),
  Animal(
    id: 'anm_003',
    ownerId: 'usr_001',
    tagId: 'KD-5510',
    name: 'Gulabi Prince (گلابی شیرا)',
    species: Species.goat,
    breed: 'Gulabi Kamori Cross',
    gender: Gender.male,
    ageMonths: 18,
    weightKg: 72,
    dob: '2025-01-10',
    purchasePrice: 75000,
    currentMarketValue: 110000,
    marketValueChangePercent: 46.6,
    importStatus: true,
    countryOfOrigin: 'Sindh Pedigree Farm',
    importLicenseNumber: 'IMP-GOAT-2025-11',
    bloodline: 'Kamori Royal Pink Line',
    sireInfo: 'Sindh Champion Stud',
    damInfo: 'Sindh Beauty Goat',
    pregnancyStatus: PregnancyStatus.none,
    milkYieldLitersPerDay: 0,
    healthScore: 96,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=800',
    ],
    vaccinationHistory: [
      VaccinationRecord(
        id: 'vac_301',
        animalId: 'anm_003',
        vaccineName: 'PPR (پپی آر بکریوں کی وبا)',
        diseaseTarget: 'Peste des Petits Ruminants',
        dateGiven: '2026-02-01',
        nextDueDate: '2027-02-01',
        administeredBy: 'Dr. Sanaullah',
        status: VaccinationStatus.completed,
      ),
    ],
    digitalLicenseNumber: 'PK-GOAT-PEDIGREE-5510',
    createdAt: '2025-01-15',
    updatedAt: '2026-07-10',
  ),
  Animal(
    id: 'anm_004',
    ownerId: 'usr_001',
    tagId: 'KD-1002',
    name: 'Sahiwal Sultan (سلطان سانڈ)',
    species: Species.cow,
    breed: 'Pure Sahiwal Stud Bull',
    gender: Gender.male,
    ageMonths: 54,
    weightKg: 710,
    dob: '2022-02-10',
    purchasePrice: 550000,
    currentMarketValue: 680000,
    marketValueChangePercent: 23.6,
    importStatus: true,
    countryOfOrigin: 'Sahiwal National Genetics Center',
    importLicenseNumber: 'NAT-GEN-2022-009',
    bloodline: 'Elite Breeding Bull A-1',
    sireInfo: 'Sahiwal Legend Sire',
    damInfo: 'Sahiwal Super Mother 30L',
    pregnancyStatus: PregnancyStatus.none,
    milkYieldLitersPerDay: 0,
    healthScore: 84,
    healthStatus: HealthStatus.fair,
    photos: [
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
    ],
    vaccinationHistory: [
      VaccinationRecord(
        id: 'vac_401',
        animalId: 'anm_004',
        vaccineName: 'FMD (منہ کھُر)',
        diseaseTarget: 'Foot & Mouth',
        dateGiven: '2026-03-10',
        nextDueDate: '2026-09-10',
        administeredBy: 'Dr. Tariq Mahmood',
        status: VaccinationStatus.completed,
      ),
    ],
    medicalHistory: [
      MedicalRecord(
        id: 'med_401',
        animalId: 'anm_004',
        date: '2026-06-20',
        diagnosis: 'Hoof Inflammation & Mild Fever',
        treatment: 'Antiseptic hoof bandage & Paracetamol Inj',
        medicineGiven: 'Meloxicam + Copper Sulphate Wash',
        dosage: '15ml IM for 2 days',
        vetName: 'Dr. Tariq Mahmood',
        recoveryStatus: RecoveryStatus.recovering,
      ),
    ],
    digitalLicenseNumber: 'PK-PEDIGREE-BULL-1002',
    createdAt: '2022-03-01',
    updatedAt: '2026-06-25',
  ),
];

final List<Animal> initialMarketplaceListings = [
  Animal(
    id: 'mkt_001',
    ownerId: 'mkt_owner_01',
    tagId: 'MND-7712',
    name: 'Sahiwal Red Champion (لال پری)',
    species: Species.cow,
    breed: 'Pure Sahiwal Grade-A',
    gender: Gender.female,
    ageMonths: 38,
    weightKg: 460,
    dob: '2023-04-10',
    purchasePrice: 310000,
    currentMarketValue: 360000,
    marketValueChangePercent: 16.1,
    importStatus: true,
    countryOfOrigin: 'Multan Mandi Breeding Center',
    pregnancyStatus: PregnancyStatus.lactating,
    milkYieldLitersPerDay: 16,
    healthScore: 94,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&q=80&w=800',
    ],
    isListedForSale: true,
    askingPrice: 355000,
    sellerName: 'Mian Tariq Hassan',
    sellerPhone: '0301-7788990',
    sellerCity: 'Multan',
    saleDescription:
        '2nd Lactation, highly dociled, verified milk capacity 16 liters/day. Complete vaccination records.',
    marketRateBenchmarkPKR: 350000,
    createdAt: '2026-07-20',
    updatedAt: '2026-08-01',
  ),
  Animal(
    id: 'mkt_002',
    ownerId: 'mkt_owner_02',
    tagId: 'MND-9904',
    name: 'Nili Ravi Queen Buffalo (نیلی شہزادی)',
    species: Species.buffalo,
    breed: 'Pure Nili Ravi Okara Breed',
    gender: Gender.female,
    ageMonths: 42,
    weightKg: 620,
    dob: '2022-11-15',
    purchasePrice: 430000,
    currentMarketValue: 510000,
    marketValueChangePercent: 18.6,
    importStatus: true,
    countryOfOrigin: 'Okara Buffalo Genetics',
    pregnancyStatus: PregnancyStatus.lactating,
    milkYieldLitersPerDay: 19,
    healthScore: 92,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
    ],
    isListedForSale: true,
    askingPrice: 500000,
    sellerName: 'Chaudhry Waseem Akram',
    sellerPhone: '0300-4455667',
    sellerCity: 'Sahiwal Mandi',
    saleDescription:
        'Top fat percentage (7.2% Fat). Quiet milking temperament, 19 liters daily.',
    marketRateBenchmarkPKR: 495000,
    createdAt: '2026-07-25',
    updatedAt: '2026-08-02',
  ),
  Animal(
    id: 'mkt_003',
    ownerId: 'mkt_owner_03',
    tagId: 'MND-3310',
    name: 'Makra Kamori Goat (مکرا گلابی گوٹ)',
    species: Species.goat,
    breed: 'Gulabi Kamori Pedigree',
    gender: Gender.female,
    ageMonths: 14,
    weightKg: 58,
    dob: '2025-05-10',
    purchasePrice: 85000,
    currentMarketValue: 125000,
    marketValueChangePercent: 47.0,
    importStatus: false,
    pregnancyStatus: PregnancyStatus.pregnant,
    pregnancyMonths: 3,
    milkYieldLitersPerDay: 3.5,
    healthScore: 95,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&q=80&w=800',
    ],
    isListedForSale: true,
    askingPrice: 120000,
    sellerName: 'Haji Gulzar Ahmed',
    sellerPhone: '0302-3344556',
    sellerCity: 'Hyderabad',
    saleDescription:
        '3 months pregnant with Kamori prize stud. Long ears (24 inches), pure pink hide.',
    marketRateBenchmarkPKR: 118000,
    createdAt: '2026-07-28',
    updatedAt: '2026-08-03',
  ),
  Animal(
    id: 'mkt_004',
    ownerId: 'mkt_owner_04',
    tagId: 'MND-5120',
    name: 'Cholistani Camel (صحرا کا رتن)',
    species: Species.camel,
    breed: 'Cholistani Mahra Camel',
    gender: Gender.male,
    ageMonths: 36,
    weightKg: 520,
    dob: '2023-08-01',
    purchasePrice: 380000,
    currentMarketValue: 460000,
    marketValueChangePercent: 21.0,
    importStatus: false,
    pregnancyStatus: PregnancyStatus.none,
    milkYieldLitersPerDay: 0,
    healthScore: 90,
    healthStatus: HealthStatus.excellent,
    photos: [
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&q=80&w=800',
    ],
    isListedForSale: true,
    askingPrice: 450000,
    sellerName: 'Sardar Rahim Yar Khan',
    sellerPhone: '0306-1122334',
    sellerCity: 'Bahawalpur',
    saleDescription:
        'Strong Cholistani riding & load camel. Healthy joints, docile temperament.',
    marketRateBenchmarkPKR: 445000,
    createdAt: '2026-07-30',
    updatedAt: '2026-08-04',
  ),
];

final List<VetDoctor> initialVets = [
  VetDoctor(
    id: 'vet_001',
    name: 'Dr. Tariq Mahmood',
    specialty: 'Senior Livestock Specialist & Surgeon',
    qualifications: 'DVM, M.Phil (UVAS Lahore)',
    experienceYears: 14,
    phone: '0301-7654321',
    clinicAddress: 'Civil Veterinary Hospital, Sahiwal City',
    city: 'Sahiwal',
    distanceKm: 4.2,
    rating: 4.9,
    consultationFeePKR: 1000,
    imageUrl:
        'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: true,
  ),
  VetDoctor(
    id: 'vet_002',
    name: 'Dr. Sanaullah Khan',
    specialty: 'Bovine Reproduction & Artificial Insemination',
    qualifications: 'DVM, MSc (Livestock Breeding)',
    experienceYears: 9,
    phone: '0333-8899001',
    clinicAddress: 'Kisan Cattle Care Clinic, G.T Road Sahiwal',
    city: 'Sahiwal',
    distanceKm: 7.8,
    rating: 4.8,
    consultationFeePKR: 800,
    imageUrl:
        'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: true,
  ),
  VetDoctor(
    id: 'vet_003',
    name: 'Dr. Faiza Malik',
    specialty: 'Veterinary Pathologist & Poultry Specialist',
    qualifications: 'DVM, PhD (Veterinary Medicine)',
    experienceYears: 11,
    phone: '0302-5544332',
    clinicAddress: 'District Livestock Diagnostic Lab, Chichawatni',
    city: 'Chichawatni',
    distanceKm: 18.5,
    rating: 4.9,
    consultationFeePKR: 1200,
    imageUrl:
        'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    availableForVideo: true,
    availableForEmergency: false,
  ),
];

final List<Appointment> initialAppointments = [
  Appointment(
    id: 'apt_101',
    farmerId: 'usr_001',
    vetId: 'vet_001',
    vetName: 'Dr. Tariq Mahmood',
    animalId: 'anm_001',
    animalName: 'Sahiwal Queen',
    date: '2026-08-08',
    timeSlot: '11:00 AM',
    type: AppointmentType.video,
    status: AppointmentStatus.confirmed,
    reason: 'Monthly pregnancy check-up & milk yield consultation',
  ),
];

final List<FarmExpense> initialExpenses = [
  FarmExpense(
    id: 'exp_001',
    date: '2026-08-01',
    category: ExpenseCategory.feed,
    amountPKR: 28500,
    description: 'Green Fodder (Berseem/Lucerne) & Wheat Straw (Bhoosa) - 50 Maunds',
  ),
  FarmExpense(
    id: 'exp_002',
    date: '2026-08-02',
    category: ExpenseCategory.feed,
    amountPKR: 18000,
    description: 'High-Protein Dairy Concentrate Feed (Vanda Wana) - 10 Bags',
  ),
  FarmExpense(
    id: 'exp_003',
    date: '2026-07-28',
    category: ExpenseCategory.medicine,
    amountPKR: 3500,
    description: 'De-worming solution & Udder Teat Dip disinfectant',
  ),
  FarmExpense(
    id: 'exp_004',
    date: '2026-07-20',
    category: ExpenseCategory.vet,
    amountPKR: 2000,
    description: 'Doctor consultation fee for Hoof treatment (Sahiwal Sultan)',
  ),
];

final List<OutbreakReport> initialOutbreaks = [
  OutbreakReport(
    id: 'out_001',
    district: 'Sahiwal',
    region: 'Chichawatni & Harappa Sector',
    diseaseName: 'Lumpy Skin Disease (لمپی سکن)',
    severity: DiseaseSeverity.moderate,
    affectedAnimalsCount: 24,
    coordinates: {'lat': 30.6682, 'lng': 73.1114},
    detectedDate: '2026-07-28',
    precautionsUrdu:
        'مچھروں اور مکھیوں کا خاتمہ کریں، متاثرہ جانور فوراً الگ رکھیں، اینٹی بائیوٹک اور ویکسینیشن فوری کروائیں۔',
    precautionsEn:
        'Eliminate flies & mosquitoes, quarantine sick cattle, administer booster vaccines.',
    status: OutbreakStatus.active,
  ),
  OutbreakReport(
    id: 'out_002',
    district: 'Okara',
    region: 'Renala Khurd Belt',
    diseaseName: 'Foot and Mouth Disease (منہ کھُر)',
    severity: DiseaseSeverity.severe,
    affectedAnimalsCount: 52,
    coordinates: {'lat': 30.8122, 'lng': 73.4473},
    detectedDate: '2026-07-20',
    precautionsUrdu:
        'فارم پر بیرونی افراد اور گاڑیوں کا داخلہ بند کریں، پوٹاشیم پرمینگنیٹ (لال دوا) سے برتن دھوئیں اور منہ دھوئیں۔',
    precautionsEn:
        'Restrict farm visitors, wash animal mouths with Potassium Permanganate solution daily.',
    status: OutbreakStatus.active,
  ),
];

final List<OfflineKnowledgeItem> offlineKnowledgeBase = [
  OfflineKnowledgeItem(
    diseaseNameUrdu: 'لمپی سکن بیماری (Lumpy Skin Disease)',
    diseaseNameEn: 'Lumpy Skin Disease (LSD)',
    symptoms: [
      'جسم پر سخت گول دانے یا گلٹیاں بننا',
      'تیز بخار (104-106 ڈگری)',
      'آنکھوں اور ناک سے پانی بہنا',
      'ٹانگوں میں سوجن اور لنگڑاہٹ',
    ],
    firstAidSteps: [
      'متاثرہ جانور کو فوری الگ باقی مویشیوں سے دور رکھیں',
      'بخار کم کرنے کے لیے ٹھنڈا پانی سر اور پیٹھ پر ڈالیں',
      'دانوں پر ڈیٹول یا پوویڈین مرہم لگائیں',
      'مکھیوں سے بچاؤ کے لیے سپرے کریں',
    ],
    commonMedicines: [
      'Meloxicam / Paracetamol Injection (بخار اور درد کے لیے)',
      'Oxytetracycline / Penicillin (انفیکشن روکنے کے لیے)',
      'Multivitamin & Liver Tonic',
    ],
    preventionGuidance:
        'سال میں ایک بار LSD کی ویکسین لازمی لگوائیں اور باڑے میں مکھی مچھر کا سپرے کروائیں۔',
  ),
  OfflineKnowledgeItem(
    diseaseNameUrdu: 'منہ کھُر بیماری (Foot and Mouth Disease)',
    diseaseNameEn: 'Foot and Mouth Disease (FMD)',
    symptoms: [
      'منہ کے اندر، زبان اور مسوڑھوں پر چھالے',
      'منہ سے لمبی لیس دار جھاگ گرنا',
      'کھُروں (سم) کے درمیان زخم اور شدید لنگڑاہٹ',
      'دودھ کی پیداوار میں اچانک شدید کمی',
    ],
    firstAidSteps: [
      'منہ کو لال دوا (Potassium Permanganate) کے ہلکے محلول سے دھوئیں',
      'سموں پر زنک آکسائیڈ یا کاپر سلفیٹ کا پیسٹ لگائیں',
      'جانور کو نرم دلیہ، سوجی یا بھیگا ہوا ونڈا کھلائیں',
    ],
    commonMedicines: [
      'Anti-inflammatory Injections (Flunixin Meglumine)',
      'Antiseptic Mouth Wash',
      'Broad-spectrum Antibiotics for secondary infection',
    ],
    preventionGuidance:
        'ہر 6 ماہ بعد FMD بائی ویلنٹ یا ٹرائی ویلنٹ ویکسین لگوائیں۔',
  ),
  OfflineKnowledgeItem(
    diseaseNameUrdu: 'مستائٹس / تھنوں کی سوجن (Mastitis)',
    diseaseNameEn: 'Mastitis (Udder Infection)',
    symptoms: [
      'تھن یا ہوانہ کا سرخ، گرم اور دردناک ہونا',
      'دودھ میں پھٹکیاں، خون یا پیپ آنا',
      'جانور کا تھن کو ہاتھ نہ لگانے دینا',
    ],
    firstAidSteps: [
      'تھن کو نیم گرم پانی اور نمک سے سیکیں',
      'متاثرہ تھن سے پورا خراب دودھ باہر نکال کر تلف کر دیں',
      'دودھ دوہنے سے پہلے اور بعد میں تھنوں کو اینٹی سیپٹک ڈِپ کریں',
    ],
    commonMedicines: [
      'Intramammary Infusion Tubes (Teat Injection)',
      'Systemic Antibiotics (Amoxicillin/Ceftiofur)',
      'Anti-swelling Antiphlogistine paste',
    ],
    preventionGuidance:
        'دودھ نکالنے والی جگہ بالکل صاف اور خشک رکھیں۔ دودھ دوہنے کے فوراً بعد جانور کو لیٹنے نہ دیں، 30 منٹ چارہ کھلائیں۔',
  ),
  OfflineKnowledgeItem(
    diseaseNameUrdu: 'گل گھوٹو (Hemorrhagic Septicemia)',
    diseaseNameEn: 'Hemorrhagic Septicemia (HS)',
    symptoms: [
      'گردن اور جھالر میں شدید دردناک سوجن',
      'سانس لینے میں شدید دشواری اور غرغراہٹ کی آواز',
      'تیز بخار اور آنکھیں سرخ ہونا',
    ],
    firstAidSteps: [
      'فوری ہنگامی طور پر ویٹرنری ڈاکٹر کو بلائیں',
      'جانور کو کھلی ہوا دار جگہ پر رکھیں',
      'گردن کی سوجن پر ٹھنڈی پٹیاں رکھیں',
    ],
    commonMedicines: [
      'High-dose Sulfadimidine Injection',
      'Ceftiofur Sodium Injection',
      'Dexamethasone / Anti-inflammatory',
    ],
    preventionGuidance:
        'برسات کے موسم سے پہلے (مئی - جون) گل گھوٹو کی ویکسین لازمی لگوائیں۔',
  ),
];

final List<DairyProduct> initialDairyProducts = [
  DairyProduct(
    id: 'dry_001',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص گائے کا دودھ (Fresh Pure Cow Milk)',
    category: DairyCategory.milk,
    pricePKR: 220,
    unit: ProductUnit.liter,
    dailyCapacity: '80 لیٹر روزانہ',
    isOrganic: true,
    inStock: true,
    description:
        '100% خالص ساہیوال گائے کا تازہ آرگینک دودھ۔ بغیر کسی ملاوٹ کے صبح اور شام تازہ دستیاب۔',
    imageUrl:
        'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    updatedAt: '2026-08-05',
  ),
  DairyProduct(
    id: 'dry_002',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص نیلی راوی بھینس کا گاڑھا دہی (Pure Thick Buffalo Yogurt)',
    category: DairyCategory.yogurt,
    pricePKR: 260,
    unit: ProductUnit.kg,
    dailyCapacity: '25 کلو روزانہ',
    isOrganic: true,
    inStock: true,
    description:
        'روایتی مٹی کی کونڈی میں جما ہوا میٹھا اور گاڑھا دہی۔ ذائقے اور صحت میں بے مثال۔',
    imageUrl:
        'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    updatedAt: '2026-08-05',
  ),
  DairyProduct(
    id: 'dry_003',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص چاٹی کا دیسی گھی (Pure Traditional Desi Ghee)',
    category: DairyCategory.ghee,
    pricePKR: 2600,
    unit: ProductUnit.kg,
    dailyCapacity: '15 کلو دستیاب',
    isOrganic: true,
    inStock: true,
    description:
        'دیسی مکھن کو ہلکی آنچ پر پکا کر تیار کردہ 100% داغدار اور خوشبودار خالص دیسی گھی۔',
    imageUrl:
        'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    updatedAt: '2026-08-04',
  ),
  DairyProduct(
    id: 'dry_004',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'تازہ چاٹی کا مکھن (Fresh Chatti White Butter)',
    category: DairyCategory.butter,
    pricePKR: 1800,
    unit: ProductUnit.kg,
    dailyCapacity: '10 کلو روزانہ',
    isOrganic: true,
    inStock: true,
    description:
        'روزانہ تازہ لسی سے نکالا گیا خالص سفید مکھن۔ نمک اور ملاوٹ سے پاک۔',
    imageUrl:
        'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    updatedAt: '2026-08-05',
  ),
  DairyProduct(
    id: 'dry_005',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'خالص تازہ کھویا برائے مٹھائی (Fresh Pure Khoya)',
    category: DairyCategory.khoya,
    pricePKR: 1200,
    unit: ProductUnit.kg,
    dailyCapacity: '20 کلو فرمائش پر',
    isOrganic: true,
    inStock: true,
    description:
        'خالص دودھ کو کڑاہی میں کاڑھ کر تیار کردہ کھویا۔ مٹھائی اور حلوا جات کے لیے بہترین۔',
    imageUrl:
        'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    updatedAt: '2026-08-03',
  ),
  DairyProduct(
    id: 'dry_006',
    farmName: 'Al-Madina Dairy & Cattle Farm',
    sellerName: 'Chaudhry Ahmed Ali',
    sellerPhone: '0300-1234567',
    sellerCity: 'Sahiwal',
    name: 'ٹھنڈی مکھن والی لسی (Chilled Chatti Lassi)',
    category: DairyCategory.lassi,
    pricePKR: 120,
    unit: ProductUnit.halfLiter,
    dailyCapacity: '100 پیکٹس روزانہ',
    isOrganic: true,
    inStock: true,
    description:
        'دہی کی لسی مکھن پیڑے اور برف کے ساتھ۔ گرمیوں کا بہترین تحفہ۔',
    imageUrl:
        'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    updatedAt: '2026-08-05',
  ),
];

