import os
import html

# Safe import for WeasyPrint (Checks if GTK/Pango libraries are available on Windows)
WEASYPRINT_WORKING = False
try:
    import weasyprint
    WEASYPRINT_WORKING = True
except (ImportError, OSError):
    WEASYPRINT_WORKING = False


def generate_pdf_report(disease_name: str, confidence: float, guidance_text: str, output_path: str = "vet_report.pdf"):
    """
    Generates a professional clinical PDF report.
    Uses WeasyPrint if GTK libraries are loaded, otherwise falls back to basic HTML-to-PDF output.
    """
    formatted_guidance = html.escape(guidance_text).replace('\n', '<br>')
    
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page {{
            size: A4;
            margin: 15mm 12mm;
            background-color: #f8fafc;
        }}
        *, *::before, *::after {{
            box-sizing: border-box;
        }}
        body {{
            margin: 0;
            padding: 0;
            font-family: 'Helvetica Neue', Arial, sans-serif;
            color: #1e293b;
            line-height: 1.6;
        }}
        .header {{
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 24px;
            border-radius: 8px;
            margin-bottom: 20px;
        }}
        .header h1 {{
            margin: 0 0 6px 0;
            font-size: 22pt;
        }}
        .header p {{
            margin: 0;
            font-size: 11pt;
            opacity: 0.9;
        }}
        .summary-card {{
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 20px;
        }}
        .summary-grid {{
            display: table;
            width: 100%;
        }}
        .summary-col {{
            display: table-cell;
            width: 50%;
            vertical-align: top;
        }}
        .metric-label {{
            font-size: 9pt;
            text-transform: uppercase;
            color: #64748b;
            font-weight: bold;
        }}
        .metric-value {{
            font-size: 14pt;
            font-weight: bold;
            color: #0f172a;
            margin-top: 4px;
        }}
        .report-section {{
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
        }}
        .report-section h2 {{
            margin-top: 0;
            color: #1e3c72;
            font-size: 14pt;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 8px;
        }}
        .content {{
            font-size: 10.5pt;
        }}
        .footer {{
            margin-top: 30px;
            text-align: center;
            font-size: 8pt;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🐄 Livestock Guardian AI</h1>
        <p>Automated Clinical Diagnostic Report & Dual-Language Veterinary Guidance</p>
    </div>

    <div class="summary-card">
        <div class="summary-grid">
            <div class="summary-col">
                <div class="metric-label">Diagnosis / تشخیص</div>
                <div class="metric-value">{disease_name.upper()}</div>
            </div>
            <div class="summary-col">
                <div class="metric-label">AI Confidence / اعتماد</div>
                <div class="metric-value">{confidence * 100:.1f}%</div>
            </div>
        </div>
    </div>

    <div class="report-section">
        <h2>📋 Diagnostic Advisory Report</h2>
        <div class="content">{formatted_guidance}</div>
    </div>

    <div class="footer">
        Generated by Livestock Guardian AI • Automated Veterinary & Farmer Assistant
    </div>
</body>
</html>
"""

    if WEASYPRINT_WORKING:
        weasyprint.HTML(string=html_content).write_pdf(output_path)
    else:
        # Fallback HTML File Output if GTK3 is not configured
        html_out_path = output_path.replace(".pdf", ".html")
        with open(html_out_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        raise RuntimeError("GTK3 Runtime for WeasyPrint is missing. Saved report as HTML instead.")

    return output_path